Add warm up, network statistics and lots of minor changes

diff --git a/load b/load
--- a/load
+++ b/load
@@ -1,20 +1,44 @@
 #!/bin/bash
 
+in=(consistency locality popularity)
+[[ $# -ne ${#in[@]} ]] && echo "Usage: $(basename $0) ${in[@]}" && exit 1
+
 set -ue
 source $CMB_HOME/env.sh
 cd $TMP_DIR
 
+check_errors() {
+  echo -e "\nErrors:"
+  for n in $(cat srv_nodes); do
+    errors=$(ssh root@$n "egrep -r \"\\[error\\]\" $RIAK_LOG_DIR || true")
+    [[ -n $errors ]] && echo $errors && exit 1
+  done
+  echo # must echo/return something
+}
+
+consist=$1
+loc=$2
+pop=$3
+
 $CMB_HOME/conf-load
 
 echo Loading
-for c in $(cat load_nodes); do
-  run_basho_bench $c bench-load.config &
-done; wait
-
-echo -e "\n\nErrors:"
-for n in $(cat srv_nodes); do
-  ssh root@$n "egrep -r \"\\[error\\]\" $RIAK_LOG_DIR || true"
-done
-
+for_all_p load_nodes "run_basho_bench \$n bench-load.config"
+check_errors
 echo "Loading finished"
+
+if [[ $consist == ev ]]; then
+  echo "Skipping warm-up"
+else
+  dur=${WARMUP_DURATION["${loc}_$pop"]} 
+  $CMB_HOME/conf-run -w lat $loc $pop $dur
+
+  echo "Warming up"
+  m0=$(riak_stats master_migrations_total)
+  for_all_p bench_nodes "run_basho_bench \$n bench-warmup.config"
+  check_errors
+  m1=$(riak_stats master_migrations_total)
+  echo "Warm-up finished ($((m1-m0)) migrations | $dur min)"
+fi
+
 exit 0
diff --git a/run b/run
--- a/run
+++ b/run
@@ -7,65 +7,56 @@ set -ue
 source $CMB_HOME/env.sh
 cd $TMP_DIR
 
-$CMB_HOME/conf-run $@
+$CMB_HOME/conf-run -r $@
 
 cur_dir=$RES_DIR/$(date +%Y%m%d_%H%M%S); mkdir -p $cur_dir
 
-riak_stats() {
-  local stat=$1
-  local total=0
-  for n in $(cat srv_nodes); do
-    v=$(ssh root@$n "$RIAK_BIN_DIR/riak-admin status | grep $stat | cut -d: -f2")
-    # to understand why, try 'i=0;j=0;((i+=j));echo $?' (and cry)
-    ((total+=v)) || true
-  done
-  echo $total
+disk_cache() {
+  agg srv_nodes "free -m | egrep Mem: | awk '{print \$7}'"
 }
 
-disk_cache() {
-  local total=0
-  for n in $(cat srv_nodes); do
-    v=$(ssh root@$n "free -m | egrep Mem:" | awk '{print $7}')
-    # to understand why, try 'i=0;j=0;((i+=j));echo $?' (and cry)
-    ((total+=v)) || true
-  done
-  echo $total
+tx_rx() {
+  local node_file=$1
+  local stat=$2
+  agg $node_file "ifconfig eth0 | egrep -o '$stat bytes:[0-9]*' | cut -d: -f2"
+}
+
+metrics() {
+  local i=$1
+  rr[$i]=$(riak_stats read_repairs_total)
+  mig[$i]=$(riak_stats master_migrations_total)
+  cache[$i]=$(disk_cache)
+  tx_srv[$i]=$(tx_rx srv_nodes TX)
+  rx_srv[$i]=$(tx_rx srv_nodes RX)
+  tx_bch[$i]=$(tx_rx bench_nodes TX)
+  rx_bch[$i]=$(tx_rx bench_nodes RX)
 }
 
 # drop cache
-for n in $(cat srv_nodes); do
-  ssh root@$n "echo 3 > /proc/sys/vm/drop_caches" &
-done; wait
-
-c0=$(riak_stats read_repairs_total)
-m0=$(riak_stats master_migrations_total)
-d0=$(disk_cache)
+echo Preparing 
+ssh_all_p srv_nodes "echo 3 > /proc/sys/vm/drop_caches"
+metrics 0
 echo Running
-for c in $(cat bench_nodes); do
-  run_basho_bench $c bench.config &
-done; wait
+for_all_p bench_nodes "run_basho_bench \$n bench.config"
+echo Getting results
+for_all_p bench_nodes "rsync -azq root@\$n:$BENCH_HOME/tests/current/ $cur_dir/bch-\$n"
+for_all_p srv_nodes "rsync -azq root@\$n:$RIAK_LOG_DIR $cur_dir/srv-\$n"
 
-for n in $(cat bench_nodes); do
-  cp bench*.config.$n $cur_dir
-  rsync -azq root@$n:$BENCH_HOME/tests/current/ $cur_dir/bch-$n &
-done; wait
-
-for n in $(cat srv_nodes); do
-  cp vm.args.$n app.config.$n $cur_dir
-  rsync -azq root@$n:$RIAK_LOG_DIR $cur_dir/srv-$n &
-done; wait
-
-c1=$(riak_stats read_repairs_total)
-m1=$(riak_stats master_migrations_total)
-d1=$(disk_cache)
-echo "conflicts=$((c1-c0))
-migrations=$((m1-m0))
-disk_cache=$((d1-d0))" > $cur_dir/metrics
+metrics 1
+echo "conflicts=$((rr[1]-rr[0]))
+migrations=$((mig[1]-mig[0]))
+disk_cache=$((cache[1]-cache[0]))
+tx_srv=$((tx_srv[1]-tx_srv[0]))
+rx_srv=$((rx_srv[1]-rx_srv[0]))
+tx_bch=$((tx_bch[1]-tx_bch[0]))
+rx_bch=$((rx_bch[1]-rx_bch[0]))" > $cur_dir/metrics
 cp conf_info $cur_dir
+cp bench*.config.* $cur_dir
+cp vm.args.* app.config.* $cur_dir
 
 echo -e "\n\nErrors:"
 # egrep exit with 1 in case of no match
-echo "Servers:"; egrep -r "\[error\]" $cur_dir || true
+echo "Servers:"; egrep -r "\[error\]" $cur_dir/srv-* || true
 echo "errors.csv:"; cat $cur_dir/bch-*/errors.csv
 
 cat $cur_dir/conf_info $cur_dir/metrics
diff --git a/run-all b/run-all
--- a/run-all
+++ b/run-all
@@ -13,22 +13,22 @@ clis=4
 # 9:1 - 91% reads / 9% writes (writes = 10% reads)
 # 1:0 - 100% reads (writes = 0% reads)
 
-ms=(ev any lat)
-rs=(0:1 1:0 9:1 1:1 3:1)
+ms=(any lat ev)
 ls=(0.5 0.9)
 ps=(uni par)
+rs=(0:1 1:0 9:1 1:1 3:1)
 ds=(0 50 100 150)
 
 [[ $# -gt 0 ]] && skip=true || skip=false
 m0=${1:-${ms[0]}}
-r0=${2:-${rs[0]}}
-l0=${3:-${ls[0]}}
-p0=${4:-${ps[0]}}
+l0=${2:-${ls[0]}}
+p0=${3:-${ps[0]}}
+r0=${4:-${rs[0]}}
 d0=${5:-${ds[0]}}
 
 match_last() {
-  [[ $m == $m0 ]] && [[ $r == $r0 ]] && [[ $l == $l0 ]] && \
-  [[ $p == $p0 ]] && [[ $d == $d0 ]] && \
+  [[ $m == $m0 ]] && [[ $l == $l0 ]] && [[ $p == $p0 ]] && \
+  [[ $r == $r0 ]] && [[ $d == $d0 ]] && \
   echo true || echo false
 }
 
@@ -43,7 +43,9 @@ est_time() {
   echo $et
 }
 
-((rem=${#ms[@]} * ${#rs[@]} * ${#ls[@]} * ${#ps[@]} * ${#ds[@]}))
+$CMB_HOME/srvs $srvs $clis
+
+((rem=${#ms[@]} * ${#ls[@]} * ${#ps[@]} * ${#rs[@]} * ${#ds[@]}))
 echo "Number of tests: $rem"
 
 started=false
@@ -51,21 +53,20 @@ exec=0
 t0=$(date +%s)
 for m in "${ms[@]}"; do
   [[ $m == ev ]] && c=ev || c=tl
+  $CMB_HOME/riak $c
 
-  if [[ $started == false ]] && ([[ $skip == false ]] || \
-     [[ $skip == true ]] && [[ $m == $m0 ]]); then
-    $CMB_HOME/srvs $srvs $clis $c
-    $CMB_HOME/delay 0
-    $CMB_HOME/start
-    $CMB_HOME/load
-    started=true
-  fi
+  for l in "${ls[@]}"; do
+    for p in "${ps[@]}"; do
+      if [[ $skip == false ]] || \
+         ([[ $m == $m0 ]] && [[ $l == $l0 ]] && [[ $p == $p0 ]]); then
+        $CMB_HOME/start
+        $CMB_HOME/load $c $l $p
+        started=true
+      fi
 
-  for r in "${rs[@]}"; do
-    for l in "${ls[@]}"; do
-      for p in "${ps[@]}"; do
+      for r in "${rs[@]}"; do
         for d in "${ds[@]}"; do
-          echo "- $m $r $l $p $d ($rem / $(est_time))"
+          echo "- $m $l $p $r $d ($rem / $(est_time))"
           ((rem--))
           if [[ $skip == true ]]; then
             [[ $(match_last) == true ]] && skip=false
@@ -74,16 +75,16 @@ for m in "${ms[@]}"; do
             sleep 15
             $CMB_HOME/delay $d
             $CMB_HOME/run $m $l $p $r
-            ((exec++)) || true # force exit status != 1
+            ((exec++)) || true # when exec == 0, exit status == 1
           fi
         done
       done
+
+      if [[ $started == true ]]; then
+        $CMB_HOME/delay 0
+        $CMB_HOME/stop
+        started=false
+      fi
     done
   done
-
-  if [[ $started == true ]]; then
-    $CMB_HOME/delay 0
-    $CMB_HOME/stop
-    started=false
-  fi
 done
